### ISSUE TITLE
Notice: Undefined property: Symfony\Component\OptionsResolver\OptionsResolver::$typeAliases

### ISSUE THREAD

**Issue by xepozz** [schmittjoh/serializer#1233]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
![image](https://user-images.githubusercontent.com/6815714/86791732-85187a00-c072-11ea-85be-d9d6335dfa0a.png)
![image](https://user-images.githubusercontent.com/6815714/86791934-a8432980-c072-11ea-838c-497000ae0ba7.png)

I've seen this one report in Sentry and decided to report about this problem to you.

<details> <summary>Full stack trace</summary>

```

ErrorException: Notice: Undefined property: Symfony\Component\OptionsResolver\OptionsResolver::$typeAliases
#72 /opt/app/vendor/jms/serializer/src/Accessor/DefaultAccessorStrategy.php(86): Symfony\Component\OptionsResolver\OptionsResolver::JMS\Serializer\Accessor\{closure}
#71 /opt/app/vendor/jms/serializer/src/Accessor/DefaultAccessorStrategy.php(91): JMS\Serializer\Accessor\DefaultAccessorStrategy::getValue
#70 /opt/app/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php(234): JMS\Serializer\GraphNavigator\SerializationGraphNavigator::accept
#69 /opt/app/vendor/jms/serializer/src/JsonSerializationVisitor.php(136): JMS\Serializer\JsonSerializationVisitor::visitProperty
#68 /opt/app/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php(241): JMS\Serializer\GraphNavigator\SerializationGraphNavigator::accept
#67 /opt/app/vendor/jms/serializer/src/JsonSerializationVisitor.php(136): JMS\Serializer\JsonSerializationVisitor::visitProperty
#66 /opt/app/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php(241): JMS\Serializer\GraphNavigator\SerializationGraphNavigator::accept
#65 /opt/app/vendor/jms/serializer/src/JsonSerializationVisitor.php(136): JMS\Serializer\JsonSerializationVisitor::visitProperty
#64 /opt/app/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php(241): JMS\Serializer\GraphNavigator\SerializationGraphNavigator::accept
#63 /opt/app/vendor/jms/serializer/src/JsonSerializationVisitor.php(136): JMS\Serializer\JsonSerializationVisitor::visitProperty
#62 /opt/app/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php(241): JMS\Serializer\GraphNavigator\SerializationGraphNavigator::accept
#61 /opt/app/vendor/jms/serializer/src/JsonSerializationVisitor.php(93): JMS\Serializer\JsonSerializationVisitor::visitArray
#60 /opt/app/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php(159): JMS\Serializer\GraphNavigator\SerializationGraphNavigator::accept
#59 /opt/app/vendor/jms/serializer/src/JsonSerializationVisitor.php(136): JMS\Serializer\JsonSerializationVisitor::visitProperty
#58 /opt/app/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php(241): JMS\Serializer\GraphNavigator\SerializationGraphNavigator::accept
#57 /opt/app/vendor/jms/serializer/src/JsonSerializationVisitor.php(136): JMS\Serializer\JsonSerializationVisitor::visitProperty
#56 /opt/app/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php(241): JMS\Serializer\GraphNavigator\SerializationGraphNavigator::accept
#55 /opt/app/vendor/jms/serializer/src/JsonSerializationVisitor.php(93): JMS\Serializer\JsonSerializationVisitor::visitArray
#54 /opt/app/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php(159): JMS\Serializer\GraphNavigator\SerializationGraphNavigator::accept
#53 /opt/app/vendor/jms/serializer/src/JsonSerializationVisitor.php(136): JMS\Serializer\JsonSerializationVisitor::visitProperty
#52 /opt/app/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php(241): JMS\Serializer\GraphNavigator\SerializationGraphNavigator::accept
#51 /opt/app/vendor/jms/serializer/src/JsonSerializationVisitor.php(136): JMS\Serializer\JsonSerializationVisitor::visitProperty
#50 /opt/app/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php(241): JMS\Serializer\GraphNavigator\SerializationGraphNavigator::accept
#49 /opt/app/vendor/jms/serializer/src/JsonSerializationVisitor.php(93): JMS\Serializer\JsonSerializationVisitor::visitArray
#48 /opt/app/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php(159): JMS\Serializer\GraphNavigator\SerializationGraphNavigator::accept
#47 /opt/app/vendor/jms/serializer/src/JsonSerializationVisitor.php(93): JMS\Serializer\JsonSerializationVisitor::visitArray
#46 /opt/app/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php(159): JMS\Serializer\GraphNavigator\SerializationGraphNavigator::accept
#45 /opt/app/vendor/jms/serializer/src/JsonSerializationVisitor.php(93): JMS\Serializer\JsonSerializationVisitor::visitArray
#44 /opt/app/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php(159): JMS\Serializer\GraphNavigator\SerializationGraphNavigator::accept
#43 /opt/app/vendor/jms/serializer/src/JsonSerializationVisitor.php(93): JMS\Serializer\JsonSerializationVisitor::visitArray
#42 /opt/app/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php(159): JMS\Serializer\GraphNavigator\SerializationGraphNavigator::accept
#41 /opt/app/vendor/jms/serializer/src/JsonSerializationVisitor.php(136): JMS\Serializer\JsonSerializationVisitor::visitProperty
#40 /opt/app/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php(241): JMS\Serializer\GraphNavigator\SerializationGraphNavigator::accept
#39 /opt/app/vendor/jms/serializer/src/JsonSerializationVisitor.php(93): JMS\Serializer\JsonSerializationVisitor::visitArray
#38 /opt/app/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php(159): JMS\Serializer\GraphNavigator\SerializationGraphNavigator::accept
#37 /opt/app/vendor/jms/serializer/src/JsonSerializationVisitor.php(136): JMS\Serializer\JsonSerializationVisitor::visitProperty
#36 /opt/app/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php(241): JMS\Serializer\GraphNavigator\SerializationGraphNavigator::accept
#35 /opt/app/vendor/jms/serializer/src/JsonSerializationVisitor.php(136): JMS\Serializer\JsonSerializationVisitor::visitProperty
#34 /opt/app/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php(241): JMS\Serializer\GraphNavigator\SerializationGraphNavigator::accept
#33 /opt/app/vendor/jms/serializer/src/JsonSerializationVisitor.php(93): JMS\Serializer\JsonSerializationVisitor::visitArray
#32 /opt/app/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php(159): JMS\Serializer\GraphNavigator\SerializationGraphNavigator::accept
#31 /opt/app/vendor/jms/serializer/src/JsonSerializationVisitor.php(136): JMS\Serializer\JsonSerializationVisitor::visitProperty
#30 /opt/app/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php(241): JMS\Serializer\GraphNavigator\SerializationGraphNavigator::accept
#29 /opt/app/vendor/jms/serializer/src/JsonSerializationVisitor.php(136): JMS\Serializer\JsonSerializationVisitor::visitProperty
#28 /opt/app/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php(241): JMS\Serializer\GraphNavigator\SerializationGraphNavigator::accept
#27 /opt/app/vendor/jms/serializer/src/JsonSerializationVisitor.php(93): JMS\Serializer\JsonSerializationVisitor::visitArray
#26 /opt/app/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php(159): JMS\Serializer\GraphNavigator\SerializationGraphNavigator::accept
#25 /opt/app/vendor/jms/serializer/src/JsonSerializationVisitor.php(93): JMS\Serializer\JsonSerializationVisitor::visitArray
#24 /opt/app/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php(159): JMS\Serializer\GraphNavigator\SerializationGraphNavigator::accept
#23 /opt/app/vendor/jms/serializer/src/JsonSerializationVisitor.php(93): JMS\Serializer\JsonSerializationVisitor::visitArray
#22 /opt/app/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php(159): JMS\Serializer\GraphNavigator\SerializationGraphNavigator::accept
#21 /opt/app/vendor/jms/serializer/src/JsonSerializationVisitor.php(136): JMS\Serializer\JsonSerializationVisitor::visitProperty
#20 /opt/app/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php(241): JMS\Serializer\GraphNavigator\SerializationGraphNavigator::accept
#19 /opt/app/vendor/jms/serializer/src/Serializer.php(249): JMS\Serializer\Serializer::visit
#18 /opt/app/vendor/jms/serializer/src/Serializer.php(162): JMS\Serializer\Serializer::serialize
#17 /opt/app/vendor/friendsofsymfony/rest-bundle/Serializer/JMSSerializerAdapter.php(60): FOS\RestBundle\Serializer\JMSSerializerAdapter::serialize
#16 /opt/app/vendor/friendsofsymfony/rest-bundle/View/ViewHandler.php(468): FOS\RestBundle\View\ViewHandler::initResponse
#15 /opt/app/vendor/friendsofsymfony/rest-bundle/View/ViewHandler.php(431): FOS\RestBundle\View\ViewHandler::createResponse
#14 /opt/app/vendor/friendsofsymfony/rest-bundle/View/ViewHandler.php(315): FOS\RestBundle\View\ViewHandler::handle
#13 /opt/app/vendor/friendsofsymfony/rest-bundle/Controller/ExceptionController.php(82): FOS\RestBundle\Controller\ExceptionController::showAction
#12 /opt/app/vendor/symfony/http-kernel/HttpKernel.php(158): Symfony\Component\HttpKernel\HttpKernel::handleRaw
#11 /opt/app/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel::handle
#10 /opt/app/vendor/symfony/http-kernel/EventListener/ErrorListener.php(60): Symfony\Component\HttpKernel\EventListener\ErrorListener::onKernelException
#9 /opt/app/vendor/friendsofsymfony/rest-bundle/EventListener/ExceptionListener.php(80): FOS\RestBundle\EventListener\ExceptionListener::onKernelException
#8 /opt/app/vendor/symfony/event-dispatcher/EventDispatcher.php(304): Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}
#7 /opt/app/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Symfony\Component\EventDispatcher\EventDispatcher::doDispatch
#6 /opt/app/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher::callListeners
#5 /opt/app/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher::dispatch
#4 /opt/app/vendor/symfony/http-kernel/HttpKernel.php(219): Symfony\Component\HttpKernel\HttpKernel::handleThrowable
#3 /opt/app/vendor/symfony/http-kernel/HttpKernel.php(112): Symfony\Component\HttpKernel\HttpKernel::terminateWithException
#2 /opt/app/vendor/symfony/http-kernel/EventListener/DebugHandlersListener.php(120): Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::Symfony\Component\HttpKernel\EventListener\{closure}
#1 /opt/app/vendor/symfony/error-handler/ErrorHandler.php(599): Symfony\Component\ErrorHandler\ErrorHandler::handleException
#0 [internal](0): null
```

</details>

**Comment by goetas** [comment]
This higlight two issuess:
1. the jms/serializer should not crash in this situation (should try to serialize static properties)
2. your code has a bug as the options-resolver should never be serialized
